# Generated by Django 4.1.2 on 2022-10-21 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('Username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=32)),
                ('Email', models.CharField(max_length=50)),
                ('About', models.CharField(max_length=500)),
                ('RoleLvl', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('PostID', models.IntegerField(primary_key=True, serialize=False)),
                ('PostFileName', models.CharField(max_length=64)),
                ('PostedWhen', models.DateTimeField()),
                ('Tags', models.CharField(max_length=500)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataTweetApi.users')),
            ],
        ),
    ]
