# Generated by Django 4.1.2 on 2022-12-07 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataTweetApi', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='File',
        ),
    ]
