# Generated by Django 4.1.2 on 2022-12-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataTweetApi', '0003_remove_posts_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='File',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
